export const API_ERRORS = {
  notSignedIn: 'not signed in',
  notYourAccount: 'not your account',
  accountNotFound: 'account not found',
  invalidNewAccount: 'invalid new account',
  invalidAccountEdits: 'invalid account edits',
  invalidDeposit: 'invalid deposit',
  invalidWithdrawal: 'invalid withdrawal',
  invalidThemeRequest: 'invalid theme request',
  unknownTheme: 'unknown theme',
  invalidViewModeRequest: 'invalid view mode request',
  unknownViewMode: 'unknown view mode',
  invalidGoal: 'invalid goal',
  goalAlreadyActive: 'a goal is already active',
  goalNotActive: 'goal is not active',
  savingsLocked: 'savings are kept until the goal is reached',
} as const;
